version: '3.8'
services:
  restapi:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"